/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luisalfred.luismaestresq2;

import javax.swing.JFileChooser;

/**
 *
 * @author luisa
 */
public class UIPrincipal extends javax.swing.JFrame {
    
    ArbolBB arbol;
    int[] arreglo;

    /**
     * Creates new form UIPrincipal
     */
    public UIPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.arbol = new ArbolBB();
        this.arreglo = new int[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subirTXTarbol = new javax.swing.JButton();
        subirTXTarreglo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comparar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recorridoArreglo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        recorridoPreorden = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        recorridoInorden = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        recorridoPosorden = new javax.swing.JTextArea();
        coincidencia = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Comparador arreglo y recorrido arbol");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        subirTXTarbol.setText("Subir TXT para el arbol");
        subirTXTarbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirTXTarbolActionPerformed(evt);
            }
        });
        jPanel1.add(subirTXTarbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        subirTXTarreglo.setText("Subir TXT para el arreglo");
        subirTXTarreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirTXTarregloActionPerformed(evt);
            }
        });
        jPanel1.add(subirTXTarreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel2.setText("Arreglo coincide con recorrido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setText("Recorrido arrelgo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setText("Recorrido preorden arbol:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setText("Recorrido inorden arbol:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel7.setText("Recorrido posorden arbol:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        comparar.setText("Comparar");
        comparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compararActionPerformed(evt);
            }
        });
        jPanel1.add(comparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        recorridoArreglo.setColumns(20);
        recorridoArreglo.setRows(5);
        jScrollPane1.setViewportView(recorridoArreglo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 80));

        recorridoPreorden.setColumns(20);
        recorridoPreorden.setRows(5);
        jScrollPane2.setViewportView(recorridoPreorden);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 294, -1, -1));

        recorridoInorden.setColumns(20);
        recorridoInorden.setRows(5);
        jScrollPane3.setViewportView(recorridoInorden);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        recorridoPosorden.setColumns(20);
        recorridoPosorden.setRows(5);
        jScrollPane4.setViewportView(recorridoPosorden);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, 90));

        coincidencia.setText("Esperando...");
        jPanel1.add(coincidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subirTXTarbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirTXTarbolActionPerformed
        Herramientas herr = new Herramientas();
        JFileChooser selectorArch = new JFileChooser();
        selectorArch.showOpenDialog(selectorArch);
        String ruta = selectorArch.getSelectedFile().getAbsolutePath();
        this.arbol = herr.leerTXTdeArbol(ruta);
    }//GEN-LAST:event_subirTXTarbolActionPerformed

    private void subirTXTarregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirTXTarregloActionPerformed
        Herramientas herr = new Herramientas();
        JFileChooser selectorArch = new JFileChooser();
        selectorArch.showOpenDialog(selectorArch);
        String ruta = selectorArch.getSelectedFile().getAbsolutePath();
        this.arreglo = herr.leerTXTdeArreglo(ruta);
        
    }//GEN-LAST:event_subirTXTarregloActionPerformed

    private void compararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compararActionPerformed
        Herramientas herr = new Herramientas();
        boolean coincidePreorden = this.arbol.compararRecorridoPreorden(arbol.getNodoRaiz(), arreglo, 0);
        boolean coincideInorden = this.arbol.compararRecorridoInorden(arbol.getNodoRaiz(), arreglo, 0);
        boolean coincidePosorden = this.arbol.compararRecorridoPosorden(arbol.getNodoRaiz(), arreglo, 0);
        if (coincidePreorden) {
            this.coincidencia.setText("Preorden");
        } else if (coincideInorden) {
            this.coincidencia.setText("Inorden");
        } else {
            this.coincidencia.setText("Posorden");
        }
        String impresionArreglo = herr.imprimirArreglo(this.arreglo);
        this.recorridoArreglo.setText(impresionArreglo);
        this.recorridoPreorden.setText(this.arbol.getImpresionPreorden());
        this.recorridoInorden.setText(this.arbol.getImpresionInorden());
        this.recorridoPosorden.setText(this.arbol.getImpresionPosorden());
    }//GEN-LAST:event_compararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coincidencia;
    private javax.swing.JButton comparar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JTextArea recorridoArreglo;
    private javax.swing.JTextArea recorridoInorden;
    private javax.swing.JTextArea recorridoPosorden;
    private javax.swing.JTextArea recorridoPreorden;
    private javax.swing.JButton subirTXTarbol;
    private javax.swing.JButton subirTXTarreglo;
    // End of variables declaration//GEN-END:variables
}
